### ISSUE TITLE
DisparitySSD

### ISSUE THREAD

**Issue by Hrayo712** [tanmaniac/IntroToComputerVision#13]
Hello, 

Hope you're doing well. I am currently trying following UD810, and was struggling a bit with PS2 algorithm, and I came accross your repository.

Hope you can clarify something on the DisparitySSD function. For the Left Disparity, you pass a negative "minDisparity" and "maxDisparity" of 0. However, to calculate search indexes, you do the following:

 **int searchIndex = fmax(0, x + minDisparity);
 int maxSearchIndex = fmin(leftPadded.cols - 1, x + maxDisparity);**

Which would mean that with a negative minDisparity, lets say: -30, and maxDisparity of 0, the searchIndex would be 0 (the first time) and maxSearchIndex equal to the window size. assuming thats right, the matrix access would go out of bounds. e.g.,  **rightPadded.at<float>(0, -5);**

I'm pretty sure I am missing something, but I cant see what. Could you clarify ? Thanks in advance for your time.

**Comment by tanmaniac** [comment]
I had forgotten how this worked, so I tried querying negative indices from an `cv::Mat` to see what would happen:

```cpp
#include <opencv2/core.hpp>
#include <iostream>

int main() {
    cv::Mat test = cv::Mat::ones(100, 100, CV_32FC1);

    auto val = test.at<float>(0, 0);
    std::cout << "val at (0, 0) = " << val << std::endl;

    auto val2 = test.at<float>(0, -1);
    std::cout << "val2 at (0, -1) = " << val2 << std::endl;
}
```

As it turns out, `cv::Mat`s do bound checking - at least in the version of OpenCV that I built. According to [`cv::Mat::at()`](https://docs.opencv.org/3.4/d3/d63/classcv_1_1Mat.html#aa5d20fc86d41d59e4d71ae93daee9726), bound checks only happen when building in a debug configuration, so I didn't have to do any explicit bounds checking myself. I got the following output when I tried to run this:

```bash
val at (0, 0) = 1
val2 at (0, -1) = 0
```

When the matrix access goes out of bounds in DisparitySSD, it just returns 0, so the cost for that pixel is simply the pixel value in the reference frame's window.

Hope this answers your question!

**Comment by Hrayo712** [comment]
Hey,

Thanks a lot for your answer, yeah it actually does. Now everything makes sense hahaha. 

Greetings from the Netherlands!
